### ISSUE TITLE
Pin position on the rotating earth is off far in some case from actual position

### ISSUE THREAD

**Issue by slord399** [JLChnToZ/vrctzhologram#1]
I understand it is beta asset and accuracy of pin position is still under development.
Just to show example of off position.
![VRChat_1920x1080_2021-07-25_16-29-03 418](https://user-images.githubusercontent.com/50810875/126904638-89126120-7ee9-4712-a55e-d6a94fed4a44.png)

IIRC, user from Japan got it to be on Palau instead around Tokyo.
It is around same time zone but as it said actual time zone name, would be nice if you can positioned pins to at least relative land instead middle of sea.

**Comment by JLChnToZ** [comment]
I know the positions is not accurate, but I still not yet to find a way to resolve it, because all coords are generated and calculated with actual time zone region files, and I tried different way tweak the generation logic, it still not going better.

If anyone have suggestion on how to achieve this, please let me know!

**Comment by slord399** [comment]
Thank you for reply.
I just checked code likely and seems fine to me.
I suspect map texture aspect issue but it seems fine as well after trying with different time zones.

At the moment, I'm suspecting tzdata.csv.
When I checked some location, it is already off actual position, some are on the wrong nations.
I will try to adjust latitude and longitude on my scene tomorrow when I get office to see if I can resolve issue with correct position data.
(Like Japan pointed to south of Kobe where timepoint located but it is on the sea, New Zealand is pointing to south of Australia which is other nation actually.)


Also when I check tzdata.csv,
I noticed location data is too precious to handle by unity I suppose so may resolve by making it like 41.65565750212268 to 41.65565 which is usually enough I believe. I also try this theory tomorrow too.

**Comment by slord399** [comment]
I repaired wrong positioning data now which caused this issue.
As I tested with few people, it seems working great.
Could you test it yourself as well?
#2 

I put individual data 1 by 1 so should be more accurate than original and it is up to 5 decimal only for prevent any calculation error.


PS: If you updated your sample world, let me know, I will seek some users to join and check who reported issue previously.
(Testing world I have is WIP world so not public yet.)

**Comment by JLChnToZ** [comment]
I have updated the demo world (both PC and Quest) with your changes in #2, feel free to test it.

**Comment by slord399** [comment]
Sorry for delay. I was busy releasing new world this weekend.
Yeah, will see how would be.
and try to think for permanent solution to make pin position be better.
(I don't know how often they may changed but it makes sense it better to be automated.)
