### ISSUE TITLE
Availability to auto switch time zones name when in Summer Time

### ISSUE THREAD

**Issue by slord399** [JLChnToZ/vrctzhologram#4]
Thank you for your asset, it is now working on my world.
On behalf of visitors, I got fist feedback for you.

Is it possible to swap time zones name when daylight saving active?

According to Wikipedia, only 49 of time zones name need to swap with name variant of daylight saving on specific time period.
[Ref](https://en.wikipedia.org/wiki/Daylight_saving_time_by_country)

Is that possible for you to have this feature?

**Comment by JLChnToZ** [comment]
I think this will very hard to implement because there will be edge cases on switiching names and the csv will have to be double sized

**Comment by slord399** [comment]
Oh, that's no good at all.
I'll reply to people suggested with your comment.
Thank you.
