### ISSUE TITLE
Asset issue

### ISSUE THREAD

**Issue by fthomys** [JLChnToZ/vrctzhologram#6]
![image](https://user-images.githubusercontent.com/73954978/192159403-fb30e444-8dee-4f53-bc8a-ffd053618e26.png)

Is it possible to fix this?

**Comment by JLChnToZ** [comment]
This is testing mode when running in editor and should not happen when build into world file. What version of U# are you using? And did you try to rebuild your world?

**Comment by fthomys** [comment]
I have the latest version of U# (1.1.1 (Version Built in VRC Creator Companion))
Also i tried to rebuild. Still same

**Comment by JLChnToZ** [comment]
Sounds weird. Did you see any error message appears when you building your world? Need more info to investigate your problem.

**Comment by fthomys** [comment]
i cant see any errors

**Comment by JLChnToZ** [comment]
Also could you check your build settings? Did it contains any compile flags that it shouldn't be there? Other than that I have no clue on why your editor is keep building the code supposed to be only for editors to the real thing.

**Comment by fthomys** [comment]
![image](https://user-images.githubusercontent.com/73954978/193451141-5ea35459-22ef-4214-9a20-9cb545fd41af.png)

**Comment by JLChnToZ** [comment]
Compiler flags are in Player Settings... Click the button at the bottom corner thanks.

**Comment by fthomys** [comment]
![image](https://user-images.githubusercontent.com/73954978/193475928-7475a99a-cfa5-4c81-80d9-1d1ca81d3e5f.png)

**Comment by JLChnToZ** [comment]
Not this tab, is "Player" tab

**Comment by woopster9865** [comment]
[<color=#FF00FF>UdonSharp</color>] Assets/TimeZoneSyncHologram/Scripts/Targets/TZHologramEntry.cs(65,39): Udon runtime exception detected!
  An exception occurred during EXTERN to 'UnityEngineTransform.__get_localPosition__UnityEngineVector3'.
      Parameter Addresses: 0x00000005, 0x00000033
  
  Object reference not set to an instance of an object


 is this because of testing rather then live? as the earth hologram only allows my time zone and when people join it does not detect the others just mine.

**Comment by JLChnToZ** [comment]
> [<color=#FF00FF>UdonSharp] Assets/TimeZoneSyncHologram/Scripts/Targets/TZHologramEntry.cs(65,39): Udon runtime exception detected! An exception occurred during EXTERN to 'UnityEngineTransform.__get_localPosition__UnityEngineVector3'. Parameter Addresses: 0x00000005, 0x00000033
> 
> Object reference not set to an instance of an object
> 
> is this because of testing rather then live? as the earth hologram only allows my time zone and when people join it does not detect the others just mine.

That line points to "text transform" property, did you check if the "text transform" of that script correctly referenced in inspector?

**Comment by woopster2k99** [comment]
sorry for late reply, i will take a look at this.
