### ISSUE TITLE
Version: 2.0.0-beta.2 does not work in testing

### ISSUE THREAD

**Issue by DrSakuu** [JLChnToZ/vrctzhologram#7]
An exception occurs in NetworkTimeSyncManagerV2.cs line 85 and the UdonBehaviour halts. This happens both in ClienSim and in local test.

Version: 2.0.0-beta.2

![20240922_105819-WHQx-Unity](https://github.com/user-attachments/assets/75f3ee06-7702-4d22-9242-49868568ef2f)

**Comment by JLChnToZ** [comment]
Thanks for report, but beta is not stable yet, as it is a complete rewrite and in heavily testing.

**Comment by JLChnToZ** [comment]
Please try beta.4 if you want to help out for testing.

I have identified this might happened because of local name conflicts.

I will close this for now and please comment/reopen if problem still persists.

**Comment by DrSakuu** [comment]
The issue persists in 2.0.0-beta.4, do these references look right?
![20240923_154432-iQrV-Unity](https://github.com/user-attachments/assets/cf08e40d-9bc9-4e3d-88d6-f5602443cb49)
![20240923_154934-FOMV-Unity](https://github.com/user-attachments/assets/d8662575-35b2-42d2-821c-957974a20056)

**Comment by JLChnToZ** [comment]
May I know your timezone settings?

A little more context, this error seems caused by fail to detect your timezone settings.

**Comment by DrSakuu** [comment]
My timezone is FLE, Windows 11 23H2
![20240923_155520-JOOZ-ApplicationFrameHost](https://github.com/user-attachments/assets/f2e5c807-eb0b-41aa-85f6-ee7e0c2dd5f4)

**Comment by JLChnToZ** [comment]
Ahh I find the cause now

This is why:
https://www.reddit.com/r/ukraine/comments/x8c897/europekiev_timezone_has_officially_been_renamed/

**Comment by JLChnToZ** [comment]
I've just updated a new version (beta.5), please check it out.

**Comment by DrSakuu** [comment]
It seems to be fixed now!

**Comment by DrSakuu** [comment]
It seems to be fixed now!
