### ISSUE TITLE
[2.0.0-beta.5] Wrong time for daylight savings

### ISSUE THREAD

**Issue by DrSakuu** [JLChnToZ/vrctzhologram#8]
The hologram shows incorrect times for some places, maybe because of daylight savings. Eastern European and Central European times are off by 1 hour, but Taiwan and Australia times are correct.
![20240923_181441-sY0G-vivaldi](https://github.com/user-attachments/assets/b3e73858-12e1-4159-ad4d-3cead647bb2c)
![20240923_181507-SOaq-vivaldi](https://github.com/user-attachments/assets/3c3ba951-296d-401b-8190-2160defa61cc)
![20240923_181531-Fz7x-vivaldi](https://github.com/user-attachments/assets/8eed6c8d-3bf0-4dca-93e5-8ff786c534d4)
![20240923_181611-DGbr-vivaldi](https://github.com/user-attachments/assets/c5c0373a-fec9-4ad6-a064-6e890db2455e)

**Comment by JLChnToZ** [comment]
Yes, I forgot to handle daylight saving times. Currently all times only shift by base offset.

**Comment by JLChnToZ** [comment]
I just updated, please check

**Comment by DrSakuu** [comment]
Thank you for the quick fixes! It is nice to see this prefab get updated again!
